version: '2'
services:
  log:
    build:
      context: .
      dockerfile: ./containers/log/Dockerfile
    image: devops_log:dev
    restart: always
    volumes:
      - /var/log/devops/:/var/log/docker/
    networks:
      - devops
    ports:
      - 15514:514
  gogits:
    build:
      context: .
      dockerfile: ./containers/gogits/Dockerfile
    image: devops_gogits:dev
    restart: always
    volumes:
      - ./config/gogits/conf/app.ini:/tmp/conf/app.ini
      - /data/devops/gogits:/data:rw
    networks:
      - devops  
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:15514"
        tag: "gogits"
  jenkins:
    build:
      context: .
      dockerfile: ./containers/jenkins/Dockerfile
    image: devops_jenkins:dev
    restart: always
    networks:
      - devops
    volumes:
      - /data/devops/jenkins_home:/var/jenkins_home
    env_file:
      - config/jenkins/env
    ports:
      - 8089:8080
    links:
      - gogits
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:15514"
        tag: "jenkins"
  daemonworker:
    build:
      context: .
      dockerfile: ./containers/daemonworker/Dockerfile
    image: devops_daemonworker:dev
    restart: always
    volumes:
      - /data/devops/data:/data
      - ./config/daemonworker/config.ini:/root/config.ini
      - ./config/daemonworker/kvm:/root/kvm
      - ./config/daemonworker/kvmregistry:/root/kvmregistry
      - ./config/daemonworker/static:/root/static
      - /data/devops/website:/root/website
    networks:
      - devops
    links:
      - gogits
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:15514"
        tag: "daemonworker"
  proxy:
    build:
      context: .
      dockerfile: ./containers/proxy/Dockerfile
    image: devops_proxy:dev
    networks:
      - devops
    restart: always
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - /data/devops/website:/data/website
    ports: 
      - 10088:80
    links:
      - daemonworker
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:15514"
        tag: "proxy"
networks:
  devops:
    external: false
